server:
 port: 3001
info:
 app:
  name: WorkoutManager
  description: Service to manage workout (CRUD)
  maintained-by: kyle
    
---

spring:
 config:
  activate:
   on-profile: local
 data:
  mongodb:
   uri: mongodb://localhost:27017/gymdb
  
---

spring:
 config:
  activate:
   on-profile: test